// Blog.js
import React, {useEffect} from 'react';
import '../styles/Blog.css';

const Blog = () => {


  useEffect(() => {
    // Load the TikTok script after a timeout to ensure the DOM has updated
    const timeoutId = setTimeout(() => {
      const script = document.createElement('script');
      script.setAttribute('src', 'https://www.tiktok.com/embed.js');
      script.setAttribute('async', true);
      document.body.appendChild(script);
    }, 0);
  
    // Clear the timeout when the component unmounts
    return () => {
      clearTimeout(timeoutId);
    };
  }, []);
  
  

  const videos = [
    {
      platform: 'YouTube',
      id: '3WkF_5M0fos', // Example YouTube video ID
      title: 'AYTO TO ΕΡΓΑΛΕΙΟ ΘΑ ΣΟΥ ΑΛΛΑΞΕΙ TH ΖΩΗ'
    },
    {
      platform : 'YouTube',
      id : 'jnl__RvSh4Y',
      title : 'ΑΠΙΣΤΕΥΤΑ ΕΡΓΑΛΕΙΑ AI'
    },
    {
      platform: 'TikTok',
      id: '7291644534109343008', // Example TikTok video ID
      title: 'EQ VS IQ'
    }
    // Include TikTok and Instagram videos similarly if their API allows embedding
  ];

  return (
    <section id="blog" className="Blog">
      <h2>Generated By Humans Greek YouTube Channel</h2>
      <div className="VideoGallery">
        {videos.map((video) => {
          const baseClass = "VideoItem";
          const classForPlatform = video.platform === 'YouTube' ? 'YouTubeVideoItem' : 'TikTokVideoItem';
          const src = video.platform === 'YouTube'
            ? `https://www.youtube.com/embed/${video.id}`
            : `https://www.tiktok.com/embed/${video.id}`;

          return (
            <div key={video.id} className={`${baseClass} ${classForPlatform}`}>
              <iframe
                src={src}
                title={video.title}
                frameBorder="0"
                allowFullScreen
                scrolling="no"
                allow="encrypted-media;"
                className="VideoIframe"
              ></iframe>
            </div>
          );
        })}
      </div>
    </section>
  );
};

export default Blog;
